version: '2'

services:
  postgres:
    image: postgres:10-alpine
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d
#      - data:/var/lib/postgresql/data
      - /srv/guacamole/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    networks:
      - guac
  guacd:
    image: guacamole/guacd:1.3.0
    restart: always
    networks:
      - guac
  guac:
    image: guacamole/guacamole:1.3.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      GUACD_HOSTNAME: guacd
      GUACD_PORT: 4822
    networks:
      - guac
    depends_on:
      - postgres
      - guacd
    
#volumes:
#  data:
#    driver: local

networks:
  guac:
    driver: bridge
